=== salman-m-aslam/television-media-ontology/tvshows.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT tvshows ANY>

<!ELEMENT AdvertisingAgency EMPTY>
<!ATTLIST AdvertisingAgency name CDATA #IMPLIED>
<!ATTLIST AdvertisingAgency advAgencyID ID #REQUIRED>

<!ELEMENT Brand EMPTY>
<!ATTLIST Brand name CDATA #IMPLIED>
<!ATTLIST Brand brandID ID #REQUIRED>

<!ELEMENT BrandRef EMPTY>
<!ATTLIST BrandRef brandID IDREF #REQUIRED>

<!ELEMENT Price (Currency, Value)>

<!ELEMENT Currency (#PCDATA)>

<!ELEMENT Value (#PCDATA)>

<!ELEMENT Type (Category+, Subcategory*)> <!-- Specifies type of a product -->

<!ELEMENT Category EMPTY>
<!ATTLIST Category categoryName CDATA "general">

<!ELEMENT Subcategory EMPTY>
<!ATTLIST Subcategory subcategoryName CDATA #REQUIRED>

<!ELEMENT Product (BrandRef+, Price, Type)> <!-- A product may be a result of a brand collaboration -->
<!ATTLIST Product prodName CDATA #IMPLIED>
<!ATTLIST Product prodID ID #REQUIRED>

<!ELEMENT Advertisement EMPTY>
<!ATTLIST Advertisement adID ID #REQUIRED>
<!ATTLIST Advertisement adDuration CDATA #REQUIRED>
<!ATTLIST Advertisement adFee CDATA "0">
<!ATTLIST Advertisement adAgency IDREF #REQUIRED>
<!ATTLIST Advertisement adProduct IDREF #REQUIRED>

<!ELEMENT MediaCompany EMPTY>
<!ATTLIST MediaCompany mcName CDATA #IMPLIED>
<!ATTLIST MediaCompany mcID ID #REQUIRED>

<!ELEMENT MediaConglomerate (MediaCompanyRef, MediaCompanyRef, MediaCompanyRef, MediaCompanyRef, MediaCompanyRef+)> <!-- A Media Conglomerate owns at least 5 Media Companies -->
<!ATTLIST MediaConglomerate mcgName CDATA #IMPLIED>
<!ATTLIST MediaConglomerate mcgID ID #REQUIRED>

<!ELEMENT MediaCompanyRef EMPTY>
<!ATTLIST MediaCompanyRef medCompID IDREF #REQUIRED>

<!ELEMENT MediaConglomerateRef EMPTY>
<!ATTLIST MediaConglomerateRef medCongID IDREF #REQUIRED>

<!-- <!ELEMENT OTTplatform ((MediaCompanyRef | MediaConglomerateRef)+)>
<!ATTLIST OTTplatform OTTname CDATA #IMPLIED>
<!ATTLIST OTTplatform OTTid ID #REQUIRED> -->

<!ELEMENT TVChannel ((MediaCompanyRef | MediaConglomerateRef)+)>
<!ATTLIST TVChannel channelName CDATA #IMPLIED>
<!ATTLIST TVChannel channelID ID #REQUIRED>

<!ELEMENT FirstName (#PCDATA)>

<!ELEMENT MiddleName (#PCDATA)>

<!ELEMENT LastName (#PCDATA)>

<!ELEMENT Name (FirstName, MiddleName*, LastName)>
<!ATTLIST Name nameType (official|nickname|titular|other) "official">

<!ELEMENT Phone EMPTY>
<!ATTLIST Phone phoneNumber CDATA #REQUIRED>
<!ATTLIST Phone areaCode CDATA "+91">

<!ELEMENT Email (#PCDATA)>

<!ELEMENT ContactInfo (Phone+, Email+)>
<!ATTLIST ContactInfo ciType (primary|secondary) "secondary">

<!ELEMENT AddressLine (#PCDATA)>

<!ELEMENT Landmark (#PCDATA)>

<!ELEMENT Address (AddressLine+, Landmark*)>
<!ATTLIST Address city CDATA "Chennai">
<!ATTLIST Address state CDATA "TamilNadu">
<!ATTLIST Address country CDATA "India">
<!ATTLIST Address pinCode CDATA "600036">

<!-- A Person does not have to be a human here -->
<!-- A Person cannot be inanimate -->
<!ELEMENT Person (Name+, ContactInfo*, Address*)>
<!ATTLIST Person personID ID #REQUIRED>
<!ATTLIST Person age CDATA "0">
<!ATTLIST Person sex (M|F) #IMPLIED>

<!ELEMENT PersonRef EMPTY>
<!ATTLIST PersonRef personID IDREF #REQUIRED>

<!ELEMENT Role (#PCDATA | CharacterRef | ShowRefs | PersonRef)* >

<!ELEMENT PlayedBy EMPTY> <!-- Specifies actor of a character -->
<!ATTLIST PlayedBy actorPlayingRole IDREF #REQUIRED>
<!ATTLIST PlayedBy status (current | past) "current">

<!ELEMENT ShowRefs EMPTY>
<!ATTLIST ShowRefs showIDs IDREFS #REQUIRED>

<!-- A Character can either be a person or an inanimate object identified by a name -->
<!-- Characters only exist in the fictional universe; they are associated with at least one show -->
<!-- A Character may not be played by any actor (e.g.) cartoon characters, characters which only get mentioned -->
<!ELEMENT Character ((Name+ | PersonRef), Role+, PlayedBy*, ShowRefs)> <!-- A character may have multiple roles in multiple situations -->
<!ATTLIST Character charID ID #REQUIRED>

<!ELEMENT CharacterRef ANY>
<!ATTLIST CharacterRef charRef IDREF #REQUIRED>

<!-- An Actor is a Person who has acted as at least one Character -->
<!ELEMENT Actor (CharacterRef+)>
<!ATTLIST Actor personID IDREF #REQUIRED>
<!ATTLIST Actor actorID ID #REQUIRED>

<!ELEMENT ProductionHouse (ContactInfo+, Address+)>
<!ATTLIST ProductionHouse phID ID #REQUIRED>
<!ATTLIST ProductionHouse phName CDATA #IMPLIED>

<!ELEMENT Show (CharacterRef+)>
<!ATTLIST Show showName CDATA #IMPLIED>
<!ATTLIST Show showID ID #REQUIRED>
<!ATTLIST Show language CDATA "Tamil">
<!ATTLIST Show episodeCount CDATA "1">
<!ATTLIST Show phID IDREF #REQUIRED> <!-- to refer to the production house which bankrolls the show -->

<!ELEMENT SequelPrequelSpinoff EMPTY>
<!ATTLIST SequelPrequelSpinoff showID IDREF #REQUIRED>
<!ATTLIST SequelPrequelSpinoff relatedShowID IDREF #REQUIRED>
<!ATTLIST SequelPrequelSpinoff relationship (prequel|sequel|spinoff) "spinoff">

<!ELEMENT Telecast EMPTY>
<!ATTLIST Telecast showID IDREF #REQUIRED>
<!ATTLIST Telecast episodeNumber CDATA #REQUIRED>
<!ATTLIST Telecast telecastType (original | repeat | premiere) "original">
<!ATTLIST Telecast duration CDATA #REQUIRED>

<!ELEMENT Slot ((Telecast | Advertisement)+)>
<!ATTLIST Slot channelID IDREF #REQUIRED>
<!ATTLIST Slot slotID ID #REQUIRED>
<!ATTLIST Slot date CDATA #REQUIRED>
<!ATTLIST Slot startTime CDATA #REQUIRED>
<!ATTLIST Slot endTime CDATA #REQUIRED>
<!ATTLIST Slot maxViewership CDATA "0">

=== salman-m-aslam/television-media-ontology/tvshows.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE tvshows SYSTEM "tvshows.dtd">

<tvshows>
    <!-- Media Companies -->
    <MediaCompany mcID="MC029" mcName="Kayal Works" />
    <MediaCompany mcID="MC025" mcName="Tulasi Productions" />
    <MediaCompany mcID="MC019" mcName="Thaazhampoo Productions" />
    <MediaCompany mcID="MC129" mcName="Arasi Network" />
    <MediaCompany mcID="MC912" mcName="Kannagi Works" />
    <MediaCompany mcID="MC009" mcName="Murugan Network" />

    <MediaCompany mcID="MC201" mcName="Star Entertainment" />
    <MediaCompany mcID="MC202" mcName="Star Movies" />
    <MediaCompany mcID="MC203" mcName="Star Sport" />
    <MediaCompany mcID="MC204" mcName="Star Kids" />
    <MediaCompany mcID="MC205" mcName="Star Infotainment" />
    <MediaCompany mcID="MC206" mcName="NDTV" />


    <!-- Media Conglomerates -->
    <MediaConglomerate mcgID="MG289" mcgName="Sooriyan Network">
        <MediaCompanyRef medCompID="MC029" />
        <MediaCompanyRef medCompID="MC025" />
        <MediaCompanyRef medCompID="MC019" />
        <MediaCompanyRef medCompID="MC129" />
        <MediaCompanyRef medCompID="MC912" />
        <MediaCompanyRef medCompID="MC009" />
    </MediaConglomerate>

    <MediaConglomerate mcgID="MG200" mcgName="Star India">
        <MediaCompanyRef medCompID="MC201" />
        <MediaCompanyRef medCompID="MC202" />
        <MediaCompanyRef medCompID="MC203" />
        <MediaCompanyRef medCompID="MC204" />
        <MediaCompanyRef medCompID="MC205" />
    </MediaConglomerate>


    <!-- TV Channels -->
    <TVChannel channelID="CH498" channelName="Sooriyan TV">
        <MediaConglomerateRef medCongID="MG289" />
    </TVChannel>

    <TVChannel channelID="CH499" channelName="Nilavu TV">
        <MediaConglomerateRef medCongID="MG289" />
    </TVChannel>

    <TVChannel channelID="CH301" channelName="StarPlus">
        <MediaCompanyRef medCompID="MC201" />
    </TVChannel>

    <TVChannel channelID="CH302" channelName="Star Bharat">
        <MediaCompanyRef medCompID="MC201" />
    </TVChannel>

    <TVChannel channelID="CH303" channelName="Star Utsav">
        <MediaCompanyRef medCompID="MC201" />
    </TVChannel>

    <TVChannel channelID="CH304" channelName="Star World">
        <MediaCompanyRef medCompID="MC201" />
    </TVChannel>

    <TVChannel channelID="CH305" channelName="Star Gold">
        <MediaCompanyRef medCompID="MC202" />
    </TVChannel>

    <TVChannel channelID="CH306" channelName="Star Movies">
        <MediaCompanyRef medCompID="MC202" />
    </TVChannel>

    <TVChannel channelID="CH307" channelName="Star Sports 1 Hindi">
        <MediaCompanyRef medCompID="MC203" />
    </TVChannel>

    <TVChannel channelID="CH308" channelName="Star Sports 1">
        <MediaCompanyRef medCompID="MC203" />
    </TVChannel>

    <TVChannel channelID="CH309" channelName="Star Sports First">
        <MediaCompanyRef medCompID="MC203" />
    </TVChannel>

    <TVChannel channelID="CH310" channelName="Star Sports 2">
        <MediaCompanyRef medCompID="MC203" />
    </TVChannel>

    <TVChannel channelID="CH311" channelName="Baby TV">
        <MediaCompanyRef medCompID="MC204" />
    </TVChannel>

    <TVChannel channelID="CH312" channelName="National Geographic India">
        <MediaCompanyRef medCompID="MC205" />
    </TVChannel>

    <TVChannel channelID="CH313" channelName="Nat Geo Wild India">
        <MediaCompanyRef medCompID="MC205" />
    </TVChannel>

    <TVChannel channelID="CH314" channelName="NDTV 24x7">
        <MediaCompanyRef medCompID="MC206" />
    </TVChannel>

    <TVChannel channelID="CH315" channelName="NDTV India ">
        <MediaCompanyRef medCompID="MC206" />
    </TVChannel>

    <TVChannel channelID="CH316" channelName="NDTV Prime">
        <MediaCompanyRef medCompID="MC206" />
    </TVChannel>


    <!-- Advertising Agencies -->
    <AdvertisingAgency name="SunMoon Advertising Agency" advAgencyID="ADVAG321" />
    <AdvertisingAgency name="Stars Advertising Agency" advAgencyID="ADVAG322" />
    <AdvertisingAgency name="Good Advertising Agency" advAgencyID="ADVAG323" />
    <AdvertisingAgency name="Bad Advertising Agency" advAgencyID="ADVAG324" />
    <AdvertisingAgency name="Ugly Advertising Agency" advAgencyID="ADVAG325" />
    <AdvertisingAgency name="Beautiful Advertising Agency" advAgencyID="ADVAG326" />
    <AdvertisingAgency name="StarBright Advertising Agency" advAgencyID="ADVAG327" />
    <AdvertisingAgency name="Kryztal Advertising Agency" advAgencyID="ADVAG328" />


    <!-- Brands -->
    <Brand name="banana" brandID="BRD321" />
    <Brand name="pineapple" brandID="BRD322" />
    <Brand name="toyola cars" brandID="BRD323" />
    <Brand name="edison cars" brandID="BRD324" />


    <!-- Products -->
    <Product prodName="myPhone13ProMaxUltra" prodID="PRD321">
        <BrandRef brandID="BRD321" />
        <Price>
            <Currency>INR</Currency>
            <Value>1000</Value>
        </Price>
        <Type>
            <Category categoryName="electronics" />
            <Subcategory subcategoryName="mobile" />
        </Type>
    </Product>

    <Product prodName="myPhone14" prodID="PRD322">
        <BrandRef brandID="BRD321" />
        <Price>
            <Currency>INR</Currency>
            <Value>2000</Value>
        </Price>
        <Type>
            <Category categoryName="electronics" />
            <Subcategory subcategoryName="mobile" />
        </Type>
    </Product>

    <Product prodName="myPhone14Mini" prodID="PRD323">
        <BrandRef brandID="BRD321" />
        <Price>
            <Currency>INR</Currency>
            <Value>3000</Value>
        </Price>
        <Type>
            <Category categoryName="electronics" />
            <Subcategory subcategoryName="mobile" />
        </Type>
    </Product>

    <Product prodName="myWatch" prodID="PRD324">
        <BrandRef brandID="BRD322" />
        <Price>
            <Currency>INR</Currency>
            <Value>30000</Value>
        </Price>
        <Type>
            <Category categoryName="electronics" />
            <Subcategory subcategoryName="smartwatch" />
        </Type>
    </Product>

    <Product prodName="toyola innola" prodID="PRD325">
        <BrandRef brandID="BRD323" />
        <Price>
            <Currency>INR</Currency>
            <Value>3000000</Value>
        </Price>
        <Type>
            <Category categoryName="vehicles" />
            <Subcategory subcategoryName="SUV" />
        </Type>
    </Product>

    <Product prodName="toyola corollary" prodID="PRD326">
        <BrandRef brandID="BRD323" />
        <Price>
            <Currency>INR</Currency>
            <Value>2000000</Value>
        </Price>
        <Type>
            <Category categoryName="vehicles" />
            <Subcategory subcategoryName="Sedan" />
        </Type>
    </Product>

    <Product prodName="edison XAEA" prodID="PRD327">
        <BrandRef brandID="BRD324" />
        <Price>
            <Currency>INR</Currency>
            <Value>20000000</Value>
        </Price>
        <Type>
            <Category categoryName="vehicles" />
            <Subcategory subcategoryName="Hatchback" />
        </Type>
    </Product>

    <Product prodName="edison XAEB" prodID="PRD328">
        <BrandRef brandID="BRD324" />
        <Price>
            <Currency>INR</Currency>
            <Value>30000000</Value>
        </Price>
        <Type>
            <Category categoryName="vehicles" />
            <Subcategory subcategoryName="Sedan" />
        </Type>
    </Product>


    <!-- People -->
    <Person personID="PRJO5" age="52" sex="M">
        <Name nameType="official">
            <FirstName>Jim</FirstName>
            <LastName>Okay</LastName>
        </Name>
    </Person>

    <Person personID="PRTT4" age="48" sex="F">
        <Name nameType="official">
            <FirstName>Tiffani</FirstName>
            <LastName>TieSang</LastName>
        </Name>
    </Person>

    <Person personID="PRMB3" age="32" sex="M">
        <Name nameType="official">
            <FirstName>Matte</FirstName>
            <LastName>Boomer</LastName>
        </Name>
    </Person>

    <Person personID="PRPB4" age="40" sex="M">
        <Name nameType="official">
            <FirstName>Peter</FirstName>
            <LastName>Burkha</LastName>
        </Name>
    </Person>

    <Person personID="PREB3" age="39" sex="F">
        <Name nameType="official">
            <FirstName>Ellie</FirstName>
            <LastName>Burkha</LastName>
        </Name>
    </Person>

    <Person personID="PRNC2" age="28" sex="M">
        <Name nameType="official">
            <FirstName>Neal</FirstName>
            <LastName>Carefree</LastName>
        </Name>
    </Person>

    <Person personID="PRNF2" age="25" sex="M">
        <Name nameType="official">
            <FirstName>Neer</FirstName>
            <LastName>Carefake</LastName>
        </Name>
    </Person>

    <Person personID="PREM1">
        <Name>
            <FirstName>Ellen</FirstName>
            <LastName>Mask</LastName>
        </Name>
        <ContactInfo>
            <Phone phoneNumber="9424242042" />
            <Email>ellen_mask@attherate.com</Email>
        </ContactInfo>
        <Address city="Chennai" state="Tamil Nadu" country="India" pinCode="600036">
            <AddressLine>107,A Hostel, IIT Madras</AddressLine>
        </Address>
    </Person>

    <Person personID="PREM2">
        <Name>
            <FirstName>Allen</FirstName>
            <LastName>Mosk</LastName>
        </Name>
        <ContactInfo>
            <Phone phoneNumber="9424242043" />
            <Email>allen_mosk@attherate.com</Email>
        </ContactInfo>
        <Address city="Chennai" state="Tamil Nadu" country="India" pinCode="600036">
            <AddressLine>108,A Hostel, IIT Madras</AddressLine>
        </Address>
    </Person>

    <Person personID="PREM3">
        <Name>
            <FirstName>Alven</FirstName>
            <LastName>Mysk</LastName>
        </Name>
